name: Rust

on:
  pull_request:
  push:
    branches: ['main']

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v3
      - name: cargo fmt
        run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v3
      - name: cargo clippy
        run: cargo clippy -- -D warnings

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test
